# Generated by Django 5.2.1 on 2025-06-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado_entrega',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='paquete',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ruta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
