# Generated by Django 5.2.1 on 2025-07-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_system', '0003_alter_estado_entrega_table_alter_paquete_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={},
        ),
    ]
