# Generated by Django 5.2.1 on 2025-07-06 21:42

from django.db import migrations

def update_ruta_polyline(apps, schema_editor):
    # Usar SQL puro para evitar problemas con el historial del modelo
    schema_editor.execute("UPDATE ruta SET ruta_polyline = '' WHERE ruta_polyline IS NULL;")

class Migration(migrations.Migration):

    dependencies = [
        ('tracking_system', '0004_alter_ruta_options'),
    ]

    operations = [
        migrations.RunPython(update_ruta_polyline, reverse_code=migrations.RunPython.noop),
    ]