# Generated by Django 5.2.1 on 2025-07-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_system', '0005_auto_20250706_2142'),
    ]

    operations = [
    ]
