# Generated by Django 5.2.1 on 2025-07-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_system', '0006_auto_20250706_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='distancia_km',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='id',
        ),
        migrations.AddField(
            model_name='ruta',
            name='ruta_destino',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='ruta_destino_latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='ruta_destino_longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='ruta_distancia_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='ruta_duracion_estimada_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='ruta_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='ruta',
            name='ruta_origen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='ruta_polyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
